-- 1. Create PROFILES table with detailed volunteer info
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'volunteer' CHECK (role IN ('admin', 'volunteer')),
  phone TEXT,
  
  -- Demographics
  city TEXT,
  address TEXT,
  bio TEXT,
  
  -- Education & Career
  college_name TEXT,
  year_of_study TEXT, -- e.g., '3rd Year', 'Graduate'
  employment_status TEXT CHECK (employment_status IN ('Student', 'Employed', 'Unemployed', 'Retired', 'Freelance')),
  
  -- Competencies
  skills TEXT[] DEFAULT '{}',    -- e.g., ['Teaching', 'Social Media', 'Event Planning']
  interests TEXT[] DEFAULT '{}', -- e.g., ['Environment', 'Healthcare']
  
  -- Performance Stats
  total_activities_count INTEGER DEFAULT 0,
  total_hours_served NUMERIC DEFAULT 0,
  last_activity_date DATE,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger to automatically update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- 2. Create EVENTS table with timing and categories
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,           -- e.g., 'Food Drive', 'Cleanliness', 'Teaching'
  event_date DATE NOT NULL,
  start_time TIME,         -- e.g., 09:00:00
  end_time TIME,           -- e.g., 17:00:00
  location TEXT,
  max_volunteers INTEGER DEFAULT 10,
  status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'ongoing', 'completed', 'cancelled')),
  
  -- Admin link
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create REGISTRATIONS table (Tracking Participation & Hours)
CREATE TABLE registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Participation Details
  attendance_status TEXT DEFAULT 'registered' CHECK (attendance_status IN ('registered', 'attended', 'no-show')),
  hours_logged NUMERIC DEFAULT 0, -- Admin sets this after the event
  feedback_comment TEXT,
  
  registration_date TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, user_id)
);

-- 4. Create ACTIVITIES table (Gallery/Impact Stats)
CREATE TABLE activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  total_beneficiaries INTEGER, -- e.g., "500 people fed"
  volunteers_involved_count INTEGER,
  impact_category TEXT,       -- matching event categories
  date_completed DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);